name=RadDSP
version=1.0.0
author=Rafael Anggit
maintainer=Rafael Anggit
sentence=A simple and optimized C++ wrapper for ESP-DSP targeting Audio.
paragraph=Provides easy-to-use classes for I2S, FFT, IIR Biquad Filters, and highly optimized FIR filters utilizing FPU accumulators on the ESP32.
category=Signal Input/Output
url=https://github.com/
architectures=esp32
depends=
