#ifndef DSP_SCHEMA_H
#define DSP_SCHEMA_H

// AUTO GENERATED BY RADSCANNER - DO NOT EDIT MANUALLY
const char* dspSchema = 
  "{\"routing\": [[\"I2S_In\", \"compL\"], [\"compL\", \"I2S0_Out\"], [\"I2S_In\", \"compR\"], [\"compR\", \"I2S0_Out\"]], "
  "\"modules\": {"
    "\"1\": {\"name\": \"compL\", \"type\": \"Dynamics\", \"params\": [\"0: Dynamics Type\", \"1: Threshold (dB)\", \"2: Ratio\", \"3: Attack (ms)\", \"4: Hold (ms)\", \"5: Release (ms)\", \"6: Makeup Gain (dB)\", \"7: SC Filter Type\", \"8: SC Freq (Hz)\", \"100: Bypass (0/1)\"]},"
    "\"2\": {\"name\": \"compR\", \"type\": \"Dynamics\", \"params\": [\"0: Dynamics Type\", \"1: Threshold (dB)\", \"2: Ratio\", \"3: Attack (ms)\", \"4: Hold (ms)\", \"5: Release (ms)\", \"6: Makeup Gain (dB)\", \"7: SC Filter Type\", \"8: SC Freq (Hz)\", \"100: Bypass (0/1)\"]}"
  "}}";

#endif // DSP_SCHEMA_H
