#ifndef DSP_SCHEMA_H
#define DSP_SCHEMA_H

// AUTO GENERATED BY RADSCANNER - DO NOT EDIT MANUALLY
const char* dspSchema = 
  "{\"routing\": [[\"I2S_In\", \"routerL\"], [\"routerL\", \"I2S0_Out\"], [\"I2S_In\", \"routerR\"], [\"routerR\", \"I2S0_Out\"]], "
  "\"modules\": {"
    "\"1\": {\"name\": \"routerL\", \"type\": \"MatrixRouter<3, 2>\", \"params\": [\"0: In0->Out0 (Lin)\", \"1: In0->Out1 (Lin)\", \"2: In1->Out0 (Lin)\", \"3: In1->Out1 (Lin)\", \"4: In2->Out0 (Lin)\", \"5: In2->Out1 (Lin)\"]},"
    "\"2\": {\"name\": \"routerR\", \"type\": \"MatrixRouter<3, 2>\", \"params\": [\"0: In0->Out0 (Lin)\", \"1: In0->Out1 (Lin)\", \"2: In1->Out0 (Lin)\", \"3: In1->Out1 (Lin)\", \"4: In2->Out0 (Lin)\", \"5: In2->Out1 (Lin)\"]}"
  "}}";

#endif // DSP_SCHEMA_H
