#ifndef DSP_SCHEMA_H
#define DSP_SCHEMA_H

// AUTO GENERATED BY RADSCANNER - DO NOT EDIT MANUALLY
const char* dspSchema = 
  "{\"routing\": [[\"I2S_In\", \"mixerL\"], [\"BT_In\", \"mixerL\"], [\"mixerL\", \"I2S0_Out\"], [\"I2S_In\", \"mixerR\"], [\"BT_In\", \"mixerR\"], [\"mixerR\", \"I2S0_Out\"]], "
  "\"modules\": {"
    "\"1\": {\"name\": \"mixerL\", \"type\": \"Mixer<2>\", \"params\": [\"0: Gain In0 (dB)\", \"1: Gain In1 (dB)\", \"100: Mute In0 (0/1)\", \"101: Mute In1 (0/1)\"]},"
    "\"2\": {\"name\": \"mixerR\", \"type\": \"Mixer<2>\", \"params\": [\"0: Gain In0 (dB)\", \"1: Gain In1 (dB)\", \"100: Mute In0 (0/1)\", \"101: Mute In1 (0/1)\"]}"
  "}}";

#endif // DSP_SCHEMA_H
