#ifndef DSP_SCHEMA_H
#define DSP_SCHEMA_H

// AUTO GENERATED BY RADSCANNER - DO NOT EDIT MANUALLY
const char* dspSchema = 
  "{\"routing\": [[\"I2S_In\", \"I2S0_Out\"]], \"modules\": {}}";

#endif // DSP_SCHEMA_H
