#ifndef DSP_SCHEMA_H
#define DSP_SCHEMA_H

// AUTO GENERATED BY RADSCANNER - DO NOT EDIT MANUALLY
const char* dspSchema = 
  "{\"routing\": [[\"I2S_In\", \"gainL\"], [\"gainL\", \"I2S0_Out\"], [\"I2S_In\", \"gainR\"], [\"gainR\", \"I2S0_Out\"]], "
  "\"modules\": {"
    "\"1\": {\"name\": \"gainL\", \"type\": \"Gain\", \"params\": [\"0: Gain (dB)\", \"1: Mute (0/1)\", \"2: Phase Invert (0/1)\"]},"
    "\"2\": {\"name\": \"gainR\", \"type\": \"Gain\", \"params\": [\"0: Gain (dB)\", \"1: Mute (0/1)\", \"2: Phase Invert (0/1)\"]}"
  "}}";

#endif // DSP_SCHEMA_H
