#ifndef DSP_SCHEMA_H
#define DSP_SCHEMA_H

// AUTO GENERATED BY RADSCANNER - DO NOT EDIT MANUALLY
const char* dspSchema = 
  "{\"routing\": [[\"I2S_In\", \"eqL\"], [\"eqL\", \"I2S0_Out\"], [\"I2S_In\", \"eqR\"], [\"eqR\", \"I2S0_Out\"]], "
  "\"modules\": {"
    "\"1\": {\"name\": \"eqL\", \"type\": \"Biquad\", \"params\": [\"0: Filter Type\", \"1: Frequency (Hz)\", \"2: Gain (dB)\", \"3: Q-Factor\", \"100: Bypass (0/1)\"]},"
    "\"2\": {\"name\": \"eqR\", \"type\": \"Biquad\", \"params\": [\"0: Filter Type\", \"1: Frequency (Hz)\", \"2: Gain (dB)\", \"3: Q-Factor\", \"100: Bypass (0/1)\"]}"
  "}}";

#endif // DSP_SCHEMA_H
