#ifndef DSP_SCHEMA_H
#define DSP_SCHEMA_H

// AUTO GENERATED BY RADSCANNER - DO NOT EDIT MANUALLY
const char* dspSchema = 
  "{\"routing\": [[\"I2S_In\", \"firL\"], [\"firL\", \"I2S0_Out\"], [\"I2S_In\", \"firR\"], [\"firR\", \"I2S0_Out\"]], "
  "\"modules\": {"
    "\"1\": {\"name\": \"firL\", \"type\": \"FIR\", \"params\": [\"3: Taps Number (16-512)\", \"4: Gain (dB)\", \"100: Bypass (0/1)\"]},"
    "\"2\": {\"name\": \"firR\", \"type\": \"FIR\", \"params\": [\"3: Taps Number (16-512)\", \"4: Gain (dB)\", \"100: Bypass (0/1)\"]}"
  "}}";

#endif // DSP_SCHEMA_H
